### ISSUE TITLE
Bug with plot_graph on windows

### ISSUE THREAD

**Issue by BillyYank** [retentioneering/retentioneering-tools#23]
При попытки построить граф, вылетает с ошибкой кодировки
![Снимок](https://user-images.githubusercontent.com/12370289/81798578-a43ed380-9529-11ea-8eec-64e4adfe3081.PNG)

**Comment by tokedo** [comment]
fixed

**Comment by tokedo** [comment]
fixed in master 22e532fca2539b23771df1a0fdfa31fce3dcc139
