### ISSUE TITLE
Error after installing via miniconda3

### ISSUE THREAD

**Issue by ivan-toriya** [retentioneering/retentioneering-tools#39]
1. Created new enviroment using miniconda3
2. `pip3 install retentioneering`
3. Got an error while starting python3 kernel «ImportError: DLL load failed while importing win32api»

Fixed it by:

```
pip install pywin32
python path\to\python\Scripts\pywin32_postinstall.py -install
```

**Comment by tokedo** [comment]
Hello, sorry for the late response. It looks like this issue is not related to Retentioneeing library. 

Thank you for sharing the solution anyway!

**Comment by tokedo** [comment]
I'll see if I can update the installer to avoid this issue. Thanks again for sharing!
