### ISSUE TITLE
Plot ENDED edge on graph plot

### ISSUE THREAD

**Issue by ivan-toriya** [retentioneering/retentioneering-tools#40]
Hi,
Is it possible to add an edge "ENDED" (like in Step Matrix) to the graph? It would helpfull to visualize from which steps the sequence was ended.

Hmm, if I'm not mistaken, it was possible in the previos version of retentioneering, no?

**Comment by ChernyshovAnton** [comment]
At the end of April 2023, we will be moving to the version 3 of the library. 
You can use pip to install packages into your beta version:
pip install retentioneering --pre

In version 3, we added a data processor [StartEndEvents](https://doc.retentioneering.com/release3/doc/user_guides/dataprocessors.html#startendevents)  that creates synthetic events of the beginning and end of the user path. Which is equivalent  ‘ENDED’ in Step Matrix.
