### ISSUE TITLE
AttributeError: 'RetentioneeringDataset' object has no attribute 'plot_graph'

### ISSUE THREAD

**Issue by StijnVanRijssel** [retentioneering/retentioneering-tools#45]
The tutorial notebook (Google Colab) returns the error above when running the following code:

```
data.rete.plot_graph(norm_type=None,
                     weight_col=None,
                     thresh=250)
```

**Comment by bilousoleksandr** [comment]
I've the same problem in Google Colab and in JupiterLab on personal machine.

**Comment by k-eduard** [comment]
Аналогичная проблема

**Comment by denmak** [comment]
Yes, looks like there is something wrong with the code in example, probably something is missing...

**Comment by denmak** [comment]
OK, solution is to downgrade version of the library, to 2.0.0 instead  latest version 2.0.2 which pip3 is installing by default.

**Comment by SiberianPM** [comment]
How do I downgrade it to 2.0.0 so I can use it in Google Colab?

**Comment by izdi** [comment]
AttributeError: 'RetentioneeringDataset' object has no attribute 'extract_features'

**Comment by bsenst** [comment]
> OK, solution is to downgrade version of the library, to 2.0.0 instead latest version 2.0.2 which pip3 is installing by default.

`!pip3 uninstall retentioneering`
`!pip3 install retentioneering==2.0.0`

**Comment by schang3-gdata** [comment]
I had the same problem, and reinstalling did not fix the issue. 
My environment is: 
`Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux`

And I already installed retentioneering-2.0.0 based on the steps above. 

The code I tried to run is straight from [the quick start](https://retentioneering.github.io/retentioneering-tools/_build/html/getting_started.html)
`data.rete.plot_graph(norm_type='full',
                     weight_col='user_id',
                     thresh=0.06,
                     targets = {'payment_done':'green',
                                'lost':'red'})`

--- Edit: Added the error code below: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-faf0eccabfb9> in <module>
----> 1 data.rete.plot_graph(norm_type='full',
      2                      weight_col='user_id',
      3                      thresh=0.06,
      4                      targets = {'payment_done':'green',
      5                                 'lost':'red'})

AttributeError: 'RetentioneeringDataset' object has no attribute 'plot_graph'

**Comment by ChernyshovAnton** [comment]
At the end of April 2023, we will be moving to the version 3 of the library. You can use pip to install packages into your beta version:
pip install retentioneering --pre
Documentation on the Transition Graph tool is available for version 3:
[User guide](https://doc.retentioneering.com/release3/doc/user_guides/transition_graph.html)
[API Reference](https://doc.retentioneering.com/release3/doc/api/tooling/transition_graph.html)
This problem is not relevant in the new major version.
