### ISSUE TITLE
The telegram link on the official website is broken

### ISSUE THREAD

**Issue by zkid18** [retentioneering/retentioneering-tools#52]
Hey folks, 
Sorry if that is not the right place for raising such kinds of issues. I was trying to navigate the community in telegram but noticed the link https://t.me/retentioneering_meetups is no longer active. 
Can you navigate me to the right one, please?

**Comment by ChernyshovAnton** [comment]
Hello! It's no problem at all. Regarding your question about the Retentioneering community on Telegram, I'm glad to inform you that we've fixed the issue and the current link is now https://t.me/Retentioneering_Announcements. This should take you to the right place. Please let us know if you have any further questions or concerns.
