### ISSUE TITLE
Plot titles and output to .png

### ISSUE THREAD

**Issue by john-graves-les-mills** [retentioneering/retentioneering-tools#60]
To support the use case of sharing plots OUTSIDE of Jupyter (such as in a PowerPoint deck), have been looking at tweaks to the Quick Start plot examples:

title = 'Sankey'
fig = stream.step_sankey(max_steps=6, threshold=0.05, show_plot=False).plot()
fig.update_layout(title=title)
fig.write_image(f"{title}.png")

title = 'Clusters'
from retentioneering.tooling.clusters import Clusters
clusters = Clusters(stream)
X = clusters.extract_features(feature_type='tfidf', ngram_range=(1, 2))
clusters.fit(method='kmeans', n_clusters=8, X=X)
fig = clusters.plot(targets=['payment_done', 'cart'])
fig.title.set_text(title)
fig.get_figure().savefig(f"{title}.png", bbox_inches='tight')

title = 'Funnel'
fig = stream.funnel(stages=['catalog', 'cart', 'payment_done'], show_plot=False).plot()
fig.update_layout(title=title)
fig.write_image(f"{title}.png")

title = 'Heatmap'
fig = stream.cohorts(
    cohort_start_unit='M',
    cohort_period=(1, 'M'),
    average=False,
    show_plot=False
).heatmap()
fig.title.set_text(title)
fig.get_figure().savefig(f"{title}.png")

Any suggestions for similar programmatic (.png) outputs for Transition Graph and Step Matrix would be appreciated.

**Comment by ChernyshovAnton** [comment]
1. The transition graph interface currently has an export feature for svg and html. Try it, it works outside of the Jupyter environment. Export to png will be added in the next library update.
![image](https://github.com/retentioneering/retentioneering-tools/assets/9435822/4f7907bb-57bd-433d-aaac-3cdcd8c6cf63)

2. We'll add a method for exporting the step matrix to png into our backlog. It's likely that we'll implement it when we roll out the interactive step matrix.

Thank you for your feedback. Were my responses helpful?

**Comment by VladislavYak** [comment]
any updates here?

> 1. The transition graph interface currently has an export feature for svg and html. Try it, it works outside of the Jupyter environment. Export to png will be added in the next library update.
>    ![image](https://private-user-images.githubusercontent.com/9435822/237527761-4f7907bb-57bd-433d-aaac-3cdcd8c6cf63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODAwMzYsIm5iZiI6MTcxMzc3OTczNiwicGF0aCI6Ii85NDM1ODIyLzIzNzUyNzc2MS00Zjc5MDdiYi01N2JkLTQzM2QtYWFhYy0zY2RjZDhjNmNmNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMDk1NTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc2YjdjY2ZhYTUwNzk4NTgwNjE2MGNkZTY1ZjJjOWE3ODE3YmYyMmIwYTMxZGU1ZjE3MDkwNTgzNzBiMzA2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sf2oHodxTrKFfIpY1y5mQWs-6C0L6L9Vt84M0rHL1zI)
> 2. We'll add a method for exporting the step matrix to png into our backlog. It's likely that we'll implement it when we roll out the interactive step matrix.
> 
> Thank you for your feedback. Were my responses helpful?
