### ISSUE TITLE
'ValueError: too many values to unpack (expected 2)' in early steps tutorial

### ISSUE THREAD

**Issue by mingghan** [retentioneering/retentioneering-tools#8]
I am getting this error on 
>data.retention.get_clusters(plot_type='cluster_heatmap')

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-ea4770463931> in <module>()
----> 1 data.retention.get_clusters(plot_type='cluster_heatmap')

/anaconda3/lib/python3.6/site-packages/retentioneering/core/utils.py in get_clusters(self, plot_type, refit_cluster, method, **kwargs)
    450         if not hasattr(self, 'clusters') or refit_cluster:
    451             clusterer = getattr(clustering, method)
--> 452             self.clusters, self._metrics = clusterer(features, **kwargs)
    453             self._create_cluster_mapping(features.index.values)
    454 

ValueError: too many values to unpack (expected 2)
```

Same on
>data.retention.get_clusters(n_clusters=8, plot_type='cluster_tsne', refit_cluster=True);

**Comment by tokedo** [comment]
try to run several times

`pip3 uninstall retentioneering`

until you see the warning message saying retentioneering is not installed. After that install the package again:

pip3 install retentioneering

**Comment by mingghan** [comment]
I reinstalled the retentioneering but it didn't help

**Comment by tokedo** [comment]
that's very odd situation. We cannot reproduce this problem. How about we have a call/zoom to take a closer look on your problem? If that's OK, you can send us contact information to retentioneering@gmail.com or submit it through our contact form at retentioneering.com/contact-us/

**Comment by mingghan** [comment]
It is all good now. Had to update my python packages
